- hosts: masternode
  roles:
       - role: "/root/roles/master"


- hosts: slavenode
  vars_prompt:
          - name: master_token
            prompt: Please Enter the master token no
            private: no
  roles:
       - role: "/configure_k8s_on_Aws/roles/slave"

        
