---
# tasks fiile for slave

- name: Add repository for kubeadm
  yum_repository:
    name: Kubernetes
    description: YUM repo for kubeadm 
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: yes
    gpgcheck: no
           
- name: Installing the Prerequisite software for k8s Cluster
  package:
          name: "{{ item }}"      
          state: present
  loop:
          - docker
          - iproute-tc
          - kubeadm   

- name: Starting the Docker & Kubelet Services
  service:
         name:  "{{ item }}"
         state: started
         enabled: yes
  loop:
          - docker
          - kubelet  

- name: Changing the Docker Cgroup Driver
  copy: 
       dest: /etc/docker/daemon.json
       content: |
            {
                "exec-opts": ["native.cgroupdriver=systemd"]
            } 
- name: Restarting the Docker Service
  service:
          name: docker 
          state: restarted


- name: Updating the iptables
  copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
         net.bridge.bridge-nf-call-ip6tables = 1
         net.bridge.bridge-nf-call-iptables = 1

- name: Loading the iptables
  shell: "sysctl --system"
          
  
- name: Joining the master node
  shell: "{{ master_token }}"



